dist: trusty

language: php

php:
  - "5.6"
  - "7.4"

addons:
  apt:
    packages:
      - libxml2-utils

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

branches:
  only:
  - master

notifications:
  email: false

env:
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

before_install:
  - composer self-update --1

install:
  - npm install
  - export DEV_LIB_PATH="vendor/xwp/wp-dev-lib/scripts"
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - source "$DEV_LIB_PATH/travis.script.sh"
  - npm run build

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"
